spring.application.name=journalApp
spring.mongodb.uri=mongodb+srv://harshadbondarde2206:mongo123@cluster0.lnfopdk.mongodb.net/journaldb
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true